// src/pages/QueueKiosk.jsx
import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence, useReducedMotion } from "framer-motion";

import { useAuth } from "../hooks/useAuth";
import { listBranches } from "../services/inventoryService";
import { joinQueue, subscribeQueueMeta, subscribeNowServing } from "../services/queueService";

const easeOut = [0.16, 1, 0.3, 1];

const makeMotion = (reduce) => ({
  page: {
    hidden: { opacity: 0, y: reduce ? 0 : 10 },
    show: {
      opacity: 1,
      y: 0,
      transition: {
        duration: reduce ? 0 : 0.45,
        ease: easeOut,
        when: "beforeChildren",
        staggerChildren: reduce ? 0 : 0.08,
      },
    },
  },
  card: {
    hidden: {
      opacity: 0,
      y: reduce ? 0 : 14,
      scale: reduce ? 1 : 0.99,
      filter: reduce ? "none" : "blur(6px)",
    },
    show: {
      opacity: 1,
      y: 0,
      scale: 1,
      filter: "blur(0px)",
      transition: reduce
        ? { duration: 0 }
        : { type: "spring", stiffness: 420, damping: 34, mass: 0.9 },
    },
  },
});

export default function QueueKiosk() {
  const navigate = useNavigate();
  const reduce = useReducedMotion();
  const m = useMemo(() => makeMotion(!!reduce), [reduce]);

  // Role-aware back button (kiosk users don't need it)
  const { profile } = useAuth();
  const role = String(profile?.role || "").toLowerCase();
  const showBack = role === "admin" || role === "pharmacist";

  const [branches, setBranches] = useState([]);
  const [branchId, setBranchId] = useState("");

  // Realtime queue status
  const [lastIssued, setLastIssued] = useState(0);
  const [serving, setServing] = useState(null);

  // Last ticket generated by this device/session
  const [lastTicket, setLastTicket] = useState(null);
  const [msg, setMsg] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    (async () => {
      const b = await listBranches();
      setBranches(b);
      if (b.length) setBranchId(b[0].id);
    })();
  }, []);

  // Realtime: queue meta + now serving (per branch)
  useEffect(() => {
    if (!branchId) return;

    let stopServing = () => {};

    const stopMeta = subscribeQueueMeta(branchId, (meta) => {
      setLastIssued(meta.currentNumber || 0);

      stopServing();
      stopServing = subscribeNowServing(branchId, meta.servingTicketId, setServing);
    });

    return () => {
      stopMeta();
      stopServing();
    };
  }, [branchId]);

  const branchName = useMemo(() => {
    return branches.find((b) => b.id === branchId)?.name || "Select a branch";
  }, [branches, branchId]);

  async function handleJoin() {
    setMsg("");
    setLastTicket(null);

    if (!branchId) return setMsg("Please select a branch.");

    try {
      setBusy(true);
      const res = await joinQueue(branchId);
      setLastTicket(res.ticketNumber);
    } catch (e) {
      console.error(e);
      setMsg(e?.message || "Failed to join queue");
    } finally {
      setBusy(false);
    }
  }

  const isBadMsg =
    String(msg || "").toLowerCase().includes("failed") ||
    String(msg || "").toLowerCase().includes("error");

  return (
    <div className="pPage queueKiosk">
      <style>{css}</style>

      <motion.div className="pShell" variants={m.page} initial="hidden" animate="show">
        {/* Header */}
        <div className="pHeader">
          <div className="pHeaderLeft">
            {showBack ? (
              <motion.button
                className="btn btnGhost"
                onClick={() => navigate(-1)}
                whileHover={busy ? undefined : reduce ? undefined : { scale: 1.02 }}
                whileTap={busy ? undefined : reduce ? undefined : { scale: 0.98 }}
                transition={reduce ? { duration: 0 } : { type: "spring", stiffness: 700, damping: 36 }}
                disabled={busy}
                aria-label="Go back"
                title="Back"
              >
                ← Back
              </motion.button>
            ) : null}

            <div className="pHeaderText">
              <div className="pTitle">Kiosk</div>
              <div className="pSubtitle">Pick branch and get your queue number</div>
            </div>
          </div>

          <div className="pHeaderRight">
            <span className="pill">Now Serving: {serving?.ticketNumber ?? "—"}</span>
            <span className="pill subtle">Latest Issued: {lastIssued || 0}</span>
          </div>
        </div>

        {/* Branch + Join */}
        <motion.section className="card" variants={m.card}>
          <div className="cardHead">
            <div>
              <div className="cardTitle">Get a queue number</div>
              <div className="cardHint">Choose your branch, then tap Join Queue</div>
            </div>
          </div>

          <div className="cardBody">
            <div className="field">
              <label className="label">Branch</label>
              <select
                value={branchId}
                onChange={(e) => setBranchId(e.target.value)}
                className="control"
                disabled={busy}
              >
                {branches.map((b) => (
                  <option key={b.id} value={b.id}>
                    {b.name}
                  </option>
                ))}
              </select>
              <div className="hint">
                Selected: <b>{branchName}</b>
              </div>
            </div>

            <motion.button
              onClick={handleJoin}
              disabled={!branchId || busy}
              className="btn btnPrimary btnBig"
              whileHover={busy ? undefined : reduce ? undefined : { scale: 1.01 }}
              whileTap={busy ? undefined : reduce ? undefined : { scale: 0.985 }}
              transition={reduce ? { duration: 0 } : { type: "spring", stiffness: 650, damping: 35 }}
            >
              {busy ? "Joining..." : "Join Queue"}
            </motion.button>

            <AnimatePresence mode="popLayout" initial={false}>
              {msg ? (
                <motion.div
                  key={msg}
                  className={isBadMsg ? "alert bad" : "alert ok"}
                  initial={{ opacity: 0, y: reduce ? 0 : 10, scale: reduce ? 1 : 0.99 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, y: reduce ? 0 : 10, scale: reduce ? 1 : 0.99 }}
                  transition={reduce ? { duration: 0 } : { duration: 0.2, ease: easeOut }}
                  layout
                >
                  {msg}
                </motion.div>
              ) : null}
            </AnimatePresence>
          </div>
        </motion.section>

        {/* Ticket result */}
        <AnimatePresence initial={false}>
          {lastTicket !== null ? (
            <motion.section
              className="card ticket"
              key="ticket"
              initial={{ opacity: 0, y: reduce ? 0 : 14, scale: reduce ? 1 : 0.99 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: reduce ? 0 : 14, scale: reduce ? 1 : 0.99 }}
              transition={reduce ? { duration: 0 } : { duration: 0.22, ease: easeOut }}
            >
              <div className="ticketTitle">Your Ticket Number</div>
              <div className="ticketNum">{lastTicket}</div>
              <div className="ticketHint">Please wait for your number to be called.</div>
            </motion.section>
          ) : null}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}

const css = `
/* =========================
   Scoped Tokens
========================= */
.queueKiosk{
  --bg0:#ffffff;
  --bg1:#f8fafc;

  --ink:#0f172a;
  --muted:#64748b;
  --muted2:#475569;

  --card: rgba(255,255,255,.86);
  --surface: rgba(255,255,255,.94);
  --surface2: rgba(248,250,252,.95);

  --stroke:#e2e8f0;
  --stroke2:#cbd5e1;
  --divider: rgba(226,232,240,.85);

  --primary:#2563eb;
  --primary-weak: rgba(37,99,235,.12);

  --success-bg:#ecfdf5;
  --success-stroke:#a7f3d0;
  --success-ink:#065f46;

  --danger-bg:#fef2f2;
  --danger-stroke:#fecaca;
  --danger-ink:#991b1b;

  --pill-bg: var(--surface);
  --pill-ink:#334155;

  --radius: 18px;
  --shadow: 0 18px 40px rgba(15,23,42,.08);
  --shadow-sm: 0 10px 20px rgba(15,23,42,.06);
}

html.dark .queueKiosk,
[data-theme="dark"] .queueKiosk{
  --bg0:#050814;
  --bg1:#0b1022;

  --ink:#e5e7eb;
  --muted:#9ca3af;
  --muted2:#cbd5e1;

  --card: rgba(15,23,42,.78);
  --surface: rgba(15,23,42,.70);
  --surface2: rgba(15,23,42,.55);

  --stroke:#1f2937;
  --stroke2:#334155;
  --divider: rgba(148,163,184,.22);

  --primary:#3b82f6;
  --primary-weak: rgba(59,130,246,.20);

  --success-bg: rgba(16,185,129,.12);
  --success-stroke: rgba(16,185,129,.35);
  --success-ink:#6ee7b7;

  --danger-bg: rgba(239,68,68,.12);
  --danger-stroke: rgba(239,68,68,.35);
  --danger-ink:#fca5a5;

  --pill-bg: var(--surface2);
  --pill-ink: var(--muted2);

  --shadow: 0 18px 40px rgba(0,0,0,.38);
  --shadow-sm: 0 10px 20px rgba(0,0,0,.28);
}

.queueKiosk *{ box-sizing:border-box; }

/* =========================
   Page Layout
========================= */
.queueKiosk.pPage{
  min-height: 100vh;
  width: 100%;
  padding: clamp(16px, 3vw, 32px);
  padding-top: 40px;

  font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;
  color: var(--ink);

  background:
    radial-gradient(1100px 520px at 14% 8%, #eef2ff 0%, rgba(238,242,255,0) 60%),
    radial-gradient(900px 520px at 90% 20%, #eff6ff 0%, rgba(239,246,255,0) 60%),
    linear-gradient(180deg, var(--bg1), var(--bg0));
}

html.dark .queueKiosk.pPage,
[data-theme="dark"] .queueKiosk.pPage{
  background:
    radial-gradient(900px 520px at 14% 8%, rgba(59,130,246,.18) 0%, rgba(59,130,246,0) 60%),
    radial-gradient(900px 520px at 90% 20%, rgba(168,85,247,.16) 0%, rgba(168,85,247,0) 60%),
    linear-gradient(180deg, var(--bg1), var(--bg0));
}

.queueKiosk .pShell{
  width: min(980px, 100%);
  margin: 0 auto;
  display: grid;
  gap: 16px;
}

/* =========================
   Header
========================= */
.queueKiosk .pHeader{
  display:flex;
  gap: 12px;
  justify-content:space-between;
  align-items:flex-start;
  flex-wrap:wrap;
  padding-bottom: 10px;
  border-bottom: 1px solid var(--divider);
}

.queueKiosk .pHeaderLeft{
  display:flex;
  gap: 12px;
  align-items:flex-start;
  flex-wrap:wrap;
}

.queueKiosk .pHeaderText{ min-width: 240px; }

.queueKiosk .pTitle{
  font-size: 22px;
  font-weight: 950;
  letter-spacing: -0.2px;
}

.queueKiosk .pSubtitle{
  font-size: 13px;
  color: var(--muted2);
  font-weight: 750;
  margin-top: 4px;
  line-height: 1.45;
}

.queueKiosk .pHeaderRight{
  display:flex;
  gap: 8px;
  align-items:center;
  flex-wrap: wrap;
}

/* =========================
   Buttons / Pills
========================= */
.queueKiosk .btn{
  height: 42px;
  padding: 0 14px;
  border-radius: 14px;
  font-weight: 950;
  cursor:pointer;
  border: 1px solid var(--stroke);
  background: var(--surface);
  color: var(--ink);
  box-shadow: var(--shadow-sm);
}

.queueKiosk .btn:disabled{ opacity: .7; cursor:not-allowed; }

.queueKiosk .btnGhost{
  background: var(--surface);
  border-color: var(--stroke);
}

.queueKiosk .btnPrimary{
  border: 1px solid rgba(37,99,235,.18);
  background: linear-gradient(180deg, #2f6cf2, var(--primary));
  color:#fff;
  box-shadow: 0 14px 26px rgba(37,99,235,.18);
}

html.dark .queueKiosk .btnPrimary,
[data-theme="dark"] .queueKiosk .btnPrimary{
  box-shadow: 0 16px 30px rgba(59,130,246,.16);
}

.queueKiosk .btnBig{ height: 56px; font-size: 16px; }

.queueKiosk .pill{
  font-size: 12px;
  font-weight: 950;
  padding: 7px 10px;
  border-radius: 999px;
  border: 1px solid var(--stroke);
  background: var(--pill-bg);
  color: var(--pill-ink);
  box-shadow: var(--shadow-sm);
  white-space: nowrap;
}

.queueKiosk .pill.subtle{
  background: var(--surface2);
  color: var(--muted2);
}

/* =========================
   Card / Form
========================= */
.queueKiosk .card{
  background: var(--card);
  border: 1px solid var(--stroke);
  border-radius: var(--radius);
  padding: 16px;
  box-shadow: var(--shadow);
  backdrop-filter: blur(8px);
}

.queueKiosk .cardHead{
  display:flex;
  justify-content:space-between;
  align-items:baseline;
  gap: 10px;
  margin-bottom: 12px;
}

.queueKiosk .cardTitle{ font-size: 16px; font-weight: 950; letter-spacing: -0.2px; }
.queueKiosk .cardHint{ font-size: 12px; color: var(--muted); font-weight: 800; margin-top: 4px; }
.queueKiosk .cardBody{ display:grid; gap: 12px; }

.queueKiosk .field{ display:grid; gap: 6px; }
.queueKiosk .label{ font-size: 12px; color: var(--muted2); font-weight: 900; }

.queueKiosk .control{
  height: 44px;
  padding: 0 12px;
  border-radius: 14px;
  border: 1px solid var(--stroke);
  outline:none;
  background: var(--surface);
  font-size: 14px;
  font-weight: 750;
  color: var(--ink);
}

.queueKiosk .control:focus{
  border-color:#93c5fd;
  box-shadow: 0 0 0 4px var(--primary-weak);
}

.queueKiosk .hint{
  font-size: 12px;
  color: var(--muted);
  font-weight: 800;
}

/* =========================
   Alerts
========================= */
.queueKiosk .alert{
  padding: 10px 12px;
  border-radius: 14px;
  border: 1px solid var(--stroke);
  background: var(--surface);
  font-size: 13px;
  font-weight: 950;
  box-shadow: var(--shadow-sm);
}

.queueKiosk .alert.ok{
  background: var(--success-bg);
  border-color: var(--success-stroke);
  color: var(--success-ink);
}

.queueKiosk .alert.bad{
  background: var(--danger-bg);
  border-color: var(--danger-stroke);
  color: var(--danger-ink);
}

/* =========================
   Ticket
========================= */
.queueKiosk .ticket{
  text-align:center;
  border-color: var(--stroke2);
}

.queueKiosk .ticketTitle{
  font-size: 12px;
  color: var(--muted);
  font-weight: 950;
}

.queueKiosk .ticketNum{
  font-size: clamp(52px, 10vw, 78px);
  font-weight: 1000;
  line-height: 1.05;
  margin-top: 10px;
  letter-spacing: -1px;
}

.queueKiosk .ticketHint{
  font-size: 13px;
  color: var(--muted);
  font-weight: 800;
  margin-top: 10px;
}
`;
